Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Xml.Serialization
Imports ListFileUIApp.FileHelpers
Imports ListFileUIApp.Infrastructure
Imports ListFileUIApp.Models
Imports ListFileUIApp.SerializerHelpers
Imports Microsoft.Office.Interop.Word
Imports Ninject
Imports Ninject.Modules

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
            CompositionRoot.Wire(new ApplicationModule())
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.ListFileUIApp.Form1
        End Sub

        Protected Overrides Sub OnRun()
            WordCreator.App = New Application()
            MyBase.OnRun()
        End Sub

        Protected Overrides Sub OnShutdown()
            MyBase.OnShutdown()
            WordCreator.App.Quit()
        End Sub
    End Class
End Namespace
